import arcade

# width & height should be multiple of TILE_SIZE
SCREEN_WIDTH = 900
SCREEN_HEIGHT = 600
TILE_SIZE = 30

UP = arcade.key.UP
RIGHT = arcade.key.RIGHT
DOWN = arcade.key.DOWN
LEFT = arcade.key.LEFT
SPACE = arcade.key.SPACE

SPRITE_TILE_SIZE = 64
APPLE_SPRITE = (0 * SPRITE_TILE_SIZE, 3 * SPRITE_TILE_SIZE)  # col=0, row=3
SNAKE_HEAD = {
    UP: (3 * SPRITE_TILE_SIZE, 0 * SPRITE_TILE_SIZE),
    RIGHT: (4 * SPRITE_TILE_SIZE, 0 * SPRITE_TILE_SIZE),
    DOWN: (4 * SPRITE_TILE_SIZE, 1 * SPRITE_TILE_SIZE),
    LEFT: (3 * SPRITE_TILE_SIZE, 1 * SPRITE_TILE_SIZE),
}
SNAKE_TAIL = {
    UP: (3 * SPRITE_TILE_SIZE, 2 * SPRITE_TILE_SIZE),
    RIGHT: (4 * SPRITE_TILE_SIZE, 2 * SPRITE_TILE_SIZE),
    DOWN: (4 * SPRITE_TILE_SIZE, 3 * SPRITE_TILE_SIZE),
    LEFT: (3 * SPRITE_TILE_SIZE, 3 * SPRITE_TILE_SIZE),
}
HORIZ_STRAIGHT = (1 * SPRITE_TILE_SIZE, 0 * SPRITE_TILE_SIZE)
VERT_STRAIGHT = (2 * SPRITE_TILE_SIZE, 1 * SPRITE_TILE_SIZE)
DOWN_RIGHT = (0 * SPRITE_TILE_SIZE, 0 * SPRITE_TILE_SIZE)
UP_RIGHT = (0 * SPRITE_TILE_SIZE, 1 * SPRITE_TILE_SIZE)
DOWN_LEFT = (2 * SPRITE_TILE_SIZE, 0 * SPRITE_TILE_SIZE)
UP_LEFT = (2 * SPRITE_TILE_SIZE, 2 * SPRITE_TILE_SIZE)
